sudo: required

language: c

services:
  - docker

install:
  - make
  - docker pull buildpack-deps:curl
  - make keyfile

script:
  - docker run --name spiped_test_d -d -v $(pwd)/keyfile:/spiped/key:ro                                                 timwolla/spiped -d -s '[0.0.0.0]:8080' -t 'example.com:80'
  - docker run --name spiped_test_e -d -v $(pwd)/keyfile:/spiped/key:ro -p 8080:8080 --link spiped_test_d:spiped_test_d timwolla/spiped -e -s '[0.0.0.0]:8080' -t 'spiped_test_d:8080'
  - "docker run --name spiped_test_curl -it --rm --link spiped_test_e:spiped_test_e buildpack-deps:curl curl -fsSL -H 'Host: example.com' http://spiped_test_e:8080 |grep '<h1>Example Domain</h1>'"
  - docker stop spiped_test_d spiped_test_e
  - docker rm spiped_test_d spiped_test_e
