language: bash
services: docker

env:
  - VERSION=3.4 VARIANT=
  - VERSION=3.3 VARIANT=
  - VERSION=3.2 VARIANT=
  - VERSION=3.1 VARIANT=

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="$(awk '$1 == "FROM" { print $2; exit }' onbuild/Dockerfile)${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
