language: bash
services: docker

env:
  - VERSION=1 VARIANT=apache
  - VERSION=1 VARIANT=fpm

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image="backdrop:$VERSION-$VARIANT"

script:
  - docker build -t "$image" .

after_script:
  - docker images
