sudo: required

language: python

python:
  - 3.6

services:
  - docker

before_install:
  - sudo sysctl -w vm.max_map_count=262144
  - sudo service docker restart
  - docker pull alpine:3.7
  - docker images

install:
  - python bootstrap.py
  - bin/buildout

script:
  - bin/test

notifications:
  email: false
