sudo: required

language: python

python:
  - 3.5

services:
  - docker

before_install:
  - docker pull alpine:3.4
  - docker images

install:
  - python bootstrap.py
  - bin/buildout

script:
  - bin/test

notifications:
  email: false
