language: bash
services: docker

env:
  - VARIANT=debian
  - VARIANT=alpine
  - VARIANT=debian ARCH=i386
  - VARIANT=alpine ARCH=i386

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VARIANT"
  - image="irssi:$VARIANT"
  - |
    (
      set -Eeuo pipefail
      set -x
      if [ -n "${ARCH:-}" ]; then
          from="$(awk '$1 == toupper("FROM") { print $2 }' Dockerfile)"
          docker pull "$ARCH/$from"
          docker tag "$ARCH/$from" "$from"
      fi
    )

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
