sudo: required

language: bash

env:
  - VERSION=1.6 VARIANT=       ARCH=
  - VERSION=1.6 VARIANT=alpine ARCH=
  - VERSION=1.6 VARIANT=       ARCH=i386
  - VERSION=1.6 VARIANT=alpine ARCH=i386

services:
  - docker

install:
  - docker pull buildpack-deps:curl

before_script:
  - image="spiped:${VERSION}${VARIANT:+-$VARIANT}"
  - "[ -n \"$ARCH\" ] && sed -i \"s!^FROM !FROM ${ARCH}/!\" ${VERSION}${VARIANT:+/$VARIANT}/Dockerfile || true"

script:
  - "docker build -t $image ${VERSION}${VARIANT:+/$VARIANT}"
  - "docker run --name spiped_generate_key      -v $(pwd):/spiped/key                                                               $image spiped-generate-key.sh"
  - "docker run --name spiped_test_d       -d   -v $(pwd)/spiped-keyfile:/spiped/key:ro                                             $image -d -s '[0.0.0.0]:8080' -t 'example.com:80'"
  - "docker run --name spiped_test_e       -d   -v $(pwd)/spiped-keyfile:/spiped/key:ro -p 80:80 --link spiped_test_d:spiped_test_d $image -e -s '[0.0.0.0]:80'   -t 'spiped_test_d:8080'"
  - "docker run --name spiped_test_curl    --link spiped_test_e:spiped_test_e buildpack-deps:curl curl -v -fsSL --connect-to '::spiped_test_e:' http://example.com |grep '<h1>Example Domain</h1>'"

after_script:
  - docker ps -a
  - docker images
