version: "2"
services:
    convertigo:
        image: "convertigo/convertigo-mbaas"
        ports:
         - "28080:28080"
        links:
         - couchdb
         - mysql
        volumes:
         - workspace:/workspace
        environment:
         - JAVA_OPTS=
           -Dconvertigo.engine.billing.enabled=true 
           -Dconvertigo.engine.billing.persistence.jdbc.username=${ANALYTICS_DB_USER} 
           -Dconvertigo.engine.billing.persistence.jdbc.password=${ANALYTICS_DB_PASSWORD}
           -Dconvertigo.engine.billing.persistence.jdbc.url=jdbc:mysql://mysql:3306/${ANALYTICS_DB}
    couchdb:
        image: "couchdb"
        ports:
         - "28081:5984"
    mysql:
        image: "mysql"
        ports:
         - "28082:3306"
        volumes:
         - analytics:/var/lib/mysql
        environment:
         - MYSQL_RANDOM_ROOT_PASSWORD=yes
         - MYSQL_DATABASE=${ANALYTICS_DB}
         - MYSQL_USER=${ANALYTICS_DB_USER}
         - MYSQL_PASSWORD=${ANALYTICS_DB_PASSWORD}
volumes:
    workspace: {}
    analytics: {}