version: 2
jobs:
  build:
    docker:
     - image: docker:latest
    environment:
     - C8O_VERSION: "7.5.0"
     - C8O_VERSION_MAJ: "7.5"
     - C8O_VERSION_PREV: "7.4.7"
     - C8O_VERSION_PREV_MAJ: "7.4"
    working_directory: /mnt
    steps:
     - checkout
     - setup_remote_docker
     - run:
         name: Docker build
         command: |
             cd $C8O_VERSION_MAJ/$C8O_VERSION
             docker build --rm=false -t convertigo/convertigo:latest .
             cd i386
             docker build --rm=false -t convertigo/convertigo:i386 .
             docker tag convertigo/convertigo:latest convertigo/convertigo:$C8O_VERSION_MAJ
             docker tag convertigo/convertigo:latest convertigo/convertigo:$C8O_VERSION
             docker tag convertigo/convertigo:i386 convertigo/convertigo:i386-$C8O_VERSION_MAJ
             docker tag convertigo/convertigo:i386 convertigo/convertigo:i386-$C8O_VERSION
     - run:
         name: Docker publish
         command: |
           docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
           docker push convertigo/convertigo:latest
           docker push convertigo/convertigo:$C8O_VERSION_MAJ
           docker push convertigo/convertigo:$C8O_VERSION
           docker push convertigo/convertigo:i386
           docker push convertigo/convertigo:i386-$C8O_VERSION_MAJ
           docker push convertigo/convertigo:i386-$C8O_VERSION
     - run:
         name: Docker build prev
         command: |
             cd $C8O_VERSION_PREV_MAJ/$C8O_VERSION_PREV
             docker build --rm=false -t convertigo/convertigo:$C8O_VERSION_PREV_MAJ .
             cd i386
             docker build --rm=false -t convertigo/convertigo:i386-$C8O_VERSION_PREV_MAJ .
             docker tag convertigo/convertigo:$C8O_VERSION_PREV_MAJ convertigo/convertigo:$C8O_VERSION_PREV
             docker tag convertigo/convertigo:i386-$C8O_VERSION_PREV_MAJ convertigo/convertigo:i386-$C8O_VERSION_PREV
     - run:
         name: Docker publish
         command: |
           docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
           docker push convertigo/convertigo:$C8O_VERSION_PREV_MAJ
           docker push convertigo/convertigo:$C8O_VERSION_PREV
           docker push convertigo/convertigo:i386-$C8O_VERSION_PREV_MAJ
           docker push convertigo/convertigo:i386-$C8O_VERSION_PREV
